name: Run Zizmor Ruleset
on:
  push:
  pull_request:

jobs:
  zizmor:
    name: Zizmor Ruleset

    permissions:
      actions: read
      contents: read

      pull-requests: write
      security-events: write

    uses: ./.github/workflows/reusable-zizmor.yml
    with:
      codeql-enabled: false
